language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: BC=1

    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: 7.0
      env: PHPSTAN=1 DEFAULT=0

    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi

  - if [[ $BC == 1 ]]; then composer remove --dev fig-r/psr2r-sniffer; fi
  - if [[ $BC == 1 ]]; then composer require --dev squizlabs/php_codesniffer:"^2.8"; fi

  - if [[ $PHPCS != 1 ]]; then composer require --dev phpunit/phpunit:"*"; fi

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml --ignore=/vendor/,/tmp/,/logs/ --extensions=php . ; fi
  - if [[ $PHPSTAN == 1 ]]; then composer require --dev phpstan/phpstan:"^0.8" && vendor/bin/phpstan analyse -c tests/phpstan.neon -l 3 src; fi

  - if [[ $CODECOVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml || true; fi
  - if [[ $CODECOVERAGE == 1 ]]; then wget -O codecov.sh https://codecov.io/bash; fi
  - if [[ $CODECOVERAGE == 1 ]]; then bash codecov.sh; fi

notifications:
  email: false
